#!/usr/bin/env bash
set -euo pipefail

CONFIG="${1:-debug}"
APP_NAME="Contextual Mac Translator"
BINARY_NAME="ContextualMacTranslator"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
# Hardened runtime is enabled via `codesign --options runtime`.
# scripts/entitlements.plist must stay COMMENT-FREE — Apple's AMFI parser
# (used by codesign) rejects XML comments inside the <dict>, even though
# `plutil -lint` accepts them. The single entitlement we enable is
# com.apple.security.cs.disable-library-validation, needed so the
# Swift runtime dylibs (libswift_Concurrency, …) can load whether they
# resolve to /usr/lib/swift or the Xcode toolchain bundle.
ENTITLEMENTS="$ROOT_DIR/scripts/entitlements.plist"

# Sparkle SUPublicEDKey — public half of the EdDSA keypair generated by
# `generate_keys` (Sparkle CLI). Private key lives in macOS Keychain on
# the signing machine. If you ever rotate this, every existing installed
# copy stops accepting updates until users upgrade manually.
SUPUBLIC_EDKEY="2cAO3CInIZ+psAKJsOz9pAntdNpxoJ0bHFl/4nzsn0A="
SU_FEED_URL="https://hoangperry.github.io/hp-translator/appcast.xml"

# Optional Developer ID signing. Export CODESIGN_IDENTITY to enable:
#   export CODESIGN_IDENTITY="Developer ID Application: <Name> (<TEAMID>)"
# When unset, the script falls back to ad-hoc signing (no Apple cert
# required; Gatekeeper will then prompt the user to right-click -> Open
# on first launch).
CODESIGN_IDENTITY="${CODESIGN_IDENTITY:-}"

cd "$ROOT_DIR"
mkdir -p "$ROOT_DIR/.build/module-cache" "$ROOT_DIR/.build/cache" "$ROOT_DIR/.build/swiftpm"
export CLANG_MODULE_CACHE_PATH="$ROOT_DIR/.build/module-cache"
export XDG_CACHE_HOME="$ROOT_DIR/.build/cache"
export SWIFTPM_HOME="$ROOT_DIR/.build/swiftpm"

swift build -c "$CONFIG"

APP_DIR="$ROOT_DIR/.build/app/$APP_NAME.app"
CONTENTS_DIR="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"
FRAMEWORKS_DIR="$CONTENTS_DIR/Frameworks"
BUILD_DIR="$ROOT_DIR/.build/$CONFIG"
ICON_SOURCE="$ROOT_DIR/scripts/AppIcon.icns"

# Sparkle.framework lives in the SPM artifacts cache. The path embeds
# the Sparkle version chosen in Package.swift — we resolve it from
# whatever SwiftPM actually downloaded.
SPARKLE_XCFW_PATH="$ROOT_DIR/.build/artifacts/sparkle/Sparkle/Sparkle.xcframework"
if [ ! -d "$SPARKLE_XCFW_PATH" ]; then
  echo "ERROR: Sparkle.xcframework not found at $SPARKLE_XCFW_PATH" >&2
  echo "       Did you run 'swift package resolve'?" >&2
  exit 1
fi
SPARKLE_FRAMEWORK_SOURCE="$SPARKLE_XCFW_PATH/macos-arm64_x86_64/Sparkle.framework"
if [ ! -d "$SPARKLE_FRAMEWORK_SOURCE" ]; then
  echo "ERROR: Sparkle.framework not found at $SPARKLE_FRAMEWORK_SOURCE" >&2
  exit 1
fi

rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR" "$FRAMEWORKS_DIR"
cp "$BUILD_DIR/$BINARY_NAME" "$MACOS_DIR/$BINARY_NAME"
cp "$ICON_SOURCE" "$RESOURCES_DIR/AppIcon.icns"

# `swift build` only bakes rpaths for the .build/ layout (it points at
# .build/artifacts/.../Sparkle.framework). Once the binary moves into
# Contents/MacOS/ and Sparkle.framework into Contents/Frameworks/, the
# binary needs an rpath that resolves there — otherwise dyld fails with
# "Library not loaded: @rpath/Sparkle.framework" and the app crashes
# at launch before any UI appears. Sparkle's install name is
# @rpath/Sparkle.framework/Versions/B/Sparkle, so the bundle-relative
# search path Contents/Frameworks/ must be on the rpath list.
if ! otool -l "$MACOS_DIR/$BINARY_NAME" | grep -q "@executable_path/../Frameworks"; then
  install_name_tool -add_rpath "@executable_path/../Frameworks" "$MACOS_DIR/$BINARY_NAME"
fi

# Copy Sparkle.framework (with full Versions/B/ tree including
# XPCServices, Updater.app, Autoupdate helper) into the app bundle.
# Use `ditto` to preserve symlinks (Versions/Current → B) and metadata.
echo "Embedding Sparkle.framework"
ditto "$SPARKLE_FRAMEWORK_SOURCE" "$FRAMEWORKS_DIR/Sparkle.framework"

cat > "$CONTENTS_DIR/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>ContextualMacTranslator</string>
  <key>CFBundleIdentifier</key>
  <string>app.lookerlab.translator</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>Contextual Mac Translator</string>
  <key>CFBundleDisplayName</key>
  <string>Contextual Mac Translator</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.11.1</string>
  <key>CFBundleVersion</key>
  <string>37</string>
  <key>LSMinimumSystemVersion</key>
  <string>14.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSAppleEventsUsageDescription</key>
  <string>Contextual Mac Translator uses keyboard automation to translate and send chat text.</string>
  <key>NSInputMonitoringUsageDescription</key>
  <string>Contextual Mac Translator listens for global hotkeys to trigger translation workflows.</string>
  <key>NSScreenCaptureUsageDescription</key>
  <string>Contextual Mac Translator uses screen capture when you trigger the OCR capture hotkey, so it can read text from any window and translate it.</string>
  <key>SUFeedURL</key>
  <string>${SU_FEED_URL}</string>
  <key>SUPublicEDKey</key>
  <string>${SUPUBLIC_EDKEY}</string>
  <key>SUEnableInstallerLauncherService</key>
  <false/>
  <key>SUEnableAutomaticChecks</key>
  <true/>
  <key>SUScheduledCheckInterval</key>
  <integer>86400</integer>
</dict>
</plist>
PLIST

# v0.10.3 — strip AppleDouble metadata files (._*) and .DS_Store BEFORE
# signing. SwiftPM extracts Sparkle.xcframework from artifacts in a way
# that leaves ._* metadata files inside the framework on macOS, and
# `ditto -c -k` faithfully includes them in the distribution ZIP. The
# files are invisible to `codesign --sign` (which signs the *real*
# files), but post-extraction `codesign --verify --deep --strict`
# treats them as "file added" foreign content and reports the bundle
# as having a "sealed resource is missing or invalid" — Gatekeeper
# then refuses to launch the app on the user's machine, and Sparkle's
# Installer.xpc fails verification mid-update. v0.10.0/v0.10.1/v0.10.2
# all shipped with this bug; v0.10.3 closes it.
echo "Stripping AppleDouble metadata before codesign..."
find "$APP_DIR" -name "._*" -delete 2>/dev/null || true
find "$APP_DIR" -name ".DS_Store" -delete 2>/dev/null || true
# `dot_clean` is the canonical Apple tool for this — handles both
# in-band ._files and resource fork forks. Belt-and-braces.
dot_clean -m "$APP_DIR" 2>/dev/null || true

# Code-signing order is non-trivial when Sparkle.framework is embedded.
# We must sign the innermost components first (XPC services with their
# own entitlements), then the framework, then the main app — otherwise
# codesign rejects the bundle. With ad-hoc signing the order matters
# less but the structure still has to be sound.
SPARKLE_VERSIONS_B="$FRAMEWORKS_DIR/Sparkle.framework/Versions/B"

if [ -n "$CODESIGN_IDENTITY" ]; then
  echo "Signing with Developer ID: $CODESIGN_IDENTITY"

  # 1. XPC services (Downloader/Installer) — preserve their pre-baked
  # entitlements; they have their own sandbox-style requirements.
  for xpc in Downloader.xpc Installer.xpc; do
    if [ -d "$SPARKLE_VERSIONS_B/XPCServices/$xpc" ]; then
      codesign --force --options runtime --timestamp \
        --preserve-metadata=entitlements,requirements,flags,runtime \
        --sign "$CODESIGN_IDENTITY" \
        "$SPARKLE_VERSIONS_B/XPCServices/$xpc"
    fi
  done

  # 2. Updater.app (the user-facing UI shown during update install)
  if [ -d "$SPARKLE_VERSIONS_B/Updater.app" ]; then
    codesign --force --options runtime --timestamp \
      --sign "$CODESIGN_IDENTITY" \
      "$SPARKLE_VERSIONS_B/Updater.app"
  fi

  # 3. Autoupdate helper binary
  if [ -f "$SPARKLE_VERSIONS_B/Autoupdate" ]; then
    codesign --force --options runtime --timestamp \
      --sign "$CODESIGN_IDENTITY" \
      "$SPARKLE_VERSIONS_B/Autoupdate"
  fi

  # 4. Sparkle.framework itself
  codesign --force --options runtime --timestamp \
    --sign "$CODESIGN_IDENTITY" \
    "$FRAMEWORKS_DIR/Sparkle.framework"

  # 5. Main app — entitlements applied here, with hardened runtime.
  # v0.10.2 — `--identifier` is set explicitly (instead of letting
  # codesign infer it from CFBundleIdentifier) so the value baked into
  # the signature is byte-stable across releases. TCC keys grants on
  # `(identifier, designated_requirement)`; any drift in the identifier
  # string would invalidate persisted permission grants on upgrade.
  codesign --force --options runtime --timestamp \
    --identifier "app.lookerlab.translator" \
    --entitlements "$ENTITLEMENTS" \
    --sign "$CODESIGN_IDENTITY" \
    "$APP_DIR"
else
  echo "Signing ad-hoc (set CODESIGN_IDENTITY to use Developer ID)"
  # Sparkle nested signing for ad-hoc, same order as above so the
  # bundle structure is recognised by Gatekeeper assessment.
  for xpc in Downloader.xpc Installer.xpc; do
    [ -d "$SPARKLE_VERSIONS_B/XPCServices/$xpc" ] && \
      codesign --force --sign - "$SPARKLE_VERSIONS_B/XPCServices/$xpc"
  done
  [ -d "$SPARKLE_VERSIONS_B/Updater.app" ] && \
    codesign --force --sign - "$SPARKLE_VERSIONS_B/Updater.app"
  [ -f "$SPARKLE_VERSIONS_B/Autoupdate" ] && \
    codesign --force --sign - "$SPARKLE_VERSIONS_B/Autoupdate"
  codesign --force --sign - "$FRAMEWORKS_DIR/Sparkle.framework"
  codesign --force --sign - "$APP_DIR"
fi
codesign --verify --strict --verbose=2 "$APP_DIR"

# v0.10.3 — second-pass strip in case any tool added ._* during the
# sign chain (rare but seen with some macOS toolchain combinations).
# Run AFTER codesign so we are removing only metadata files, not any
# real code signature artifact.
find "$APP_DIR" -name "._*" -delete 2>/dev/null || true
find "$APP_DIR" -name ".DS_Store" -delete 2>/dev/null || true

# v0.10.3 — final invariant check. If `codesign --verify --deep
# --strict` or `spctl --assess` fails here, the bundle WILL fail on
# the user's machine after Sparkle extracts it. Better to fail the
# build than to ship another broken release.
echo "Verifying bundle is launch-ready (deep + strict + Gatekeeper)…"
codesign --verify --deep --strict --verbose=2 "$APP_DIR" 2>&1 | tail -3
if [ -n "$CODESIGN_IDENTITY" ]; then
  # Notarization staple isn't done yet at this point of the script
  # (caller does that post-notary), so spctl will reject for missing
  # ticket — that's expected. We only re-verify the sealed-resources
  # invariant via codesign here; the caller's notary+staple+verify
  # flow handles Gatekeeper acceptance after stapling.
  echo "Note: Gatekeeper acceptance is verified by the caller after staple."
fi

echo "$APP_DIR"
